### ISSUE TITLE
Python's async IO or threads to make sure API requests aren't blocking

### ISSUE THREAD

**Issue by Sathiyakugan** [asgardeo/asgardeo-auth-python-sdk#2]
Currently, the SDK doesn't consider using Python's async IO or threads to make sure API requests aren't blocking. This could be okay for the time being but going forward, I think it will make the SDK a lot faster if we can do these asynchronously.

**Comment by DonOmalVindula** [comment]
Closing the issue as this repo is no longer maintained.
