### ISSUE TITLE
sdk not running properly

### ISSUE THREAD

**Issue by faizanshah512** [asgardeo/asgardeo-auth-python-sdk#28]
its very bad your team not providing a good docuementation

**Comment by AfraHussaindeen** [comment]
Currently we are working on improving the Python SDK and the documentation. 
Note : A quick start guide is provided via the PR https://github.com/asgardeo/asgardeo-auth-python-sdk/pull/31

**Comment by VivekVinushanth** [comment]
We had a documentation restructuring effort recently and Asgardeo Python SDK docs were also updated as a part of that effort. You can visit the updated and improved docs for Python SDK [here](https://github.com/asgardeo/asgardeo-auth-python-sdk/blob/main/README.md). Please check it out and let us know your feedback.
